# Website details
name: Leonardo Silva
description: Full Stack Developer
email: leonardoplxy@gmail.com
author: leonardosilva
lang: pt
locale: pt_BR

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/Fortaleza
paginateLabel: pagina
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://leonardo1065a.github.io/

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
